id: D14B7B07A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:44:30+00:00'
last_modified: '2022-05-26T11:46:38.694295+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '2737':
      image_group_id: I1PD95872
      title: རྩ་བའི་ལྟུང་བའི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1953
      order: 27
      base_file: 2737.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
