id: P96C2445A
initial_creation_type: ocr
source_metadata:
  volumes:
    4549e77b89634f65bb21a95b48003610:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: རྩ་བའི་ལྟུང་བའི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1953
      volume_number: 27
